#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

#define HEAL_LOCATION_NONE 0
#define HEAL_LOCATION_DEMO_TOWN 1
#define HEAL_LOCATION_BATTLE_FRONTIER_OUTSIDE_EAST 2
#define HEAL_LOCATION_COUNT 3

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
