gText_Birch_Welcome::
	.string "Welcome to pokeemerald-expansion's\n"
	.string "Demo Town for v1.9.3!\p"
	.string "This is NOT a game in on itself, but\n"
	.string "a base for you to make your own games!\p"
	.string "If you were sold this software,\n"
	.string "demand your money back!\p"
	.string "This opening sequence was made using C,\n"
	.string "which lets you do advanced stuff...\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "It also how gender choosing and\n"
	.string "naming the player happens.\p"
	.string "You'll want to check “src/main_menu.c”\n"
	.string "if you want to edit this sequence.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Now...$"

gText_Birch_BoyOrGirl::
	.string "Choose your gender.$"

gText_Birch_WhatsYourName::
	.string "Choose your name. Leaving it blank will\n"
	.string "choose randomly between default ones.$"

gText_Birch_SoItsPlayer::
	.string "{PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Understood!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "You'll be warped to Demo Town now,\n"
	.string "But without the shaking from the\l"
	.string "original game's truck sequence.\p"
	.string "Search for “ExecuteTruckSequence” to\n"
	.string "see how you can reenable it.\p"
	.string "$"
