name: 🙏 Feature Request 🙏
description: Do you want a feature to be added to the Expansion? Let us know!
labels: ["feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill in all fields with as many details as possible.
  - type: textarea
    id: behavior
    attributes:
      label: Behavior Description
      description: |
        What is the current behavior? What behavior would you expect your feature request to provide? What other information can you provide to help your feature get implemented?
      placeholder: |
        Provide as much context as possible. 
    validations:
      required: true
  - type: textarea
    id: media
    attributes:
      label: media
      description: |
        Have other projects or games solved this problem? Do you have images or video to show this happening?
      placeholder: |
        Here you can also attach log screenshots, gifs or a video, or provide links to other projects.
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Discord contact info
      description: Provide your Discord tag here so we can contact you in case we need more details. Be sure to join our server ([here](https://discord.gg/6CzjAG6GZk)).
      placeholder: ex. Lunos#4026
    validations:
      required: false
